// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/BaseButton.vue')['default']
    BaseIcon: typeof import('./components/BaseIcon.vue')['default']
    BaseInput: typeof import('./components/BaseInput.vue')['default']
    BaseRouter: typeof import('./components/BaseRouter.vue')['default']
    BaseSpace: typeof import('./components/BaseSpace.vue')['default']
    BaseTabs: typeof import('./components/BaseTabs.vue')['default']
    BaseToggle: typeof import('./components/BaseToggle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
  }
}
